Traceback (most recent call last):
  File "/home/dominique/anaconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/dominique/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dominique/anaconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dominique/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dominique/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/dominique/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/dominique/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.scatter(y, lin_model.predict(X_poly))

xline = np.linspace(0,70000,100)
plt.plot(xline, xline, '--r')

residuals3 = y-lin_model.predict(X_poly)
MSE3 = (residuals3**2).mean()
print(MSE3)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[15], line 1[0m
[0;32m----> 1[0m plt[38;5;241m.[39mscatter(y, lin_model[38;5;241m.[39mpredict(X_poly))
[1;32m      3[0m xline [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m,[38;5;241m70000[39m,[38;5;241m100[39m)
[1;32m      4[0m plt[38;5;241m.[39mplot(xline, xline, [38;5;124m'[39m[38;5;124m--r[39m[38;5;124m'[39m)

File [0;32m~/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_base.py:306[0m, in [0;36mLinearModel.predict[0;34m(self, X)[0m
[1;32m    292[0m [38;5;28;01mdef[39;00m [38;5;21mpredict[39m([38;5;28mself[39m, X):
[1;32m    293[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    294[0m [38;5;124;03m    Predict using the linear model.[39;00m
[1;32m    295[0m 
[0;32m   (...)[0m
[1;32m    304[0m [38;5;124;03m        Returns predicted values.[39;00m
[1;32m    305[0m [38;5;124;03m    """[39;00m
[0;32m--> 306[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_decision_function(X)

File [0;32m~/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_base.py:285[0m, in [0;36mLinearModel._decision_function[0;34m(self, X)[0m
[1;32m    282[0m [38;5;28;01mdef[39;00m [38;5;21m_decision_function[39m([38;5;28mself[39m, X):
[1;32m    283[0m     check_is_fitted([38;5;28mself[39m)
[0;32m--> 285[0m     X [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_validate_data(X, accept_sparse[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mcsr[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mcsc[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mcoo[39m[38;5;124m"[39m], reset[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m    286[0m     coef_ [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcoef_
[1;32m    287[0m     [38;5;28;01mif[39;00m coef_[38;5;241m.[39mndim [38;5;241m==[39m [38;5;241m1[39m:

File [0;32m~/anaconda3/lib/python3.12/site-packages/sklearn/base.py:654[0m, in [0;36mBaseEstimator._validate_data[0;34m(self, X, y, reset, validate_separately, cast_to_ndarray, **check_params)[0m
[1;32m    651[0m     out [38;5;241m=[39m X, y
[1;32m    653[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m no_val_X [38;5;129;01mand[39;00m check_params[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mensure_2d[39m[38;5;124m"[39m, [38;5;28;01mTrue[39;00m):
[0;32m--> 654[0m     [38;5;28mself[39m[38;5;241m.[39m_check_n_features(X, reset[38;5;241m=[39mreset)
[1;32m    656[0m [38;5;28;01mreturn[39;00m out

File [0;32m~/anaconda3/lib/python3.12/site-packages/sklearn/base.py:443[0m, in [0;36mBaseEstimator._check_n_features[0;34m(self, X, reset)[0m
[1;32m    440[0m     [38;5;28;01mreturn[39;00m
[1;32m    442[0m [38;5;28;01mif[39;00m n_features [38;5;241m!=[39m [38;5;28mself[39m[38;5;241m.[39mn_features_in_:
[0;32m--> 443[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    444[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mX has [39m[38;5;132;01m{[39;00mn_features[38;5;132;01m}[39;00m[38;5;124m features, but [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;124m"[39m
[1;32m    445[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mis expecting [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mn_features_in_[38;5;132;01m}[39;00m[38;5;124m features as input.[39m[38;5;124m"[39m
[1;32m    446[0m     )

[0;31mValueError[0m: X has 35 features, but LinearRegression is expecting 7 features as input.

